### ISSUE TITLE
supervisor died

### ISSUE THREAD

**Issue by Razzer90** [Alexandre-io/homeassistant-vcontrol#18]
`[20:29:12] INFO: Sending command: [setBetriebArtM1]: WW
[71] Mon Jan 30 20:29:48 2023 : Client connected 127.0.0.1:45036 (FD:5)
[19:29:48] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[71] Mon Jan 30 20:29:48 2023 : Received SIGTERM
[19:29:48] INFO: vlclient_pub Service restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
[19:29:48] WARNING: Halt add-on with exit code 1
[19:29:48] INFO: vclient_sub Service restart after closing
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

i found a new bug, when i trigger a set command, the addon crashes completely. but the command is executed correctly!

**Comment by Bjoern3003** [comment]
Did you have tried with Version 1.8.2? In my environment, it's working fine.

![1675109454](https://user-images.githubusercontent.com/13675579/215584601-42819542-f2f9-433b-9297-6319dc7915f7.png)

**Comment by Razzer90** [comment]
jep, its the 1.8.2!

**Comment by Schm1tz1** [comment]
Hmm, might be that now the return value parsing works as intended... 🤔 
@Bjoern3003 can you check what set-command caused the crash? What device id are you using?

**Comment by Bjoern3003** [comment]
How should I check the chrash? I can not reproduce the crash in my setup.

**Comment by Schm1tz1** [comment]
Oh, sorry, wanted to mention @Razzer90. Can you give some more details?

**Comment by Schm1tz1** [comment]
Ok, now I'm getting the same after a few minutes...
```
[21:01:52] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
[21:01:52] INFO: vlclient_pub Service restart after closing
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
```

**Comment by Schm1tz1** [comment]
@Razzer90 @Bjoern3003 In my case it was concurrent telnet connections from my actual HA instance, a testing instance and a local telnet client messing up everything... I could see many connections in the vcontrold log and failing commands because there have been calls from different clients at the same time... Exiting the clients and restarting the service fixed it for me.

**Comment by Razzer90** [comment]
> @Razzer90 @Bjoern3003 In my case it was concurrent telnet connections from my actual HA instance, a testing instance and a local telnet client messing up everything... I could see many connections in the vcontrold log and failing commands because there have been calls from different clients at the same time... Exiting the clients and restarting the service fixed it for me.

That is the solution! If I trigger telnet commands via terminal, the addon crashes! simply no second telnet access...thanks for the great work!

**Comment by Schm1tz1** [comment]
@Razzer90 - cool, thanks for the feedback, good to know that there is no additional surprise. @Alexandre-io - I think this issue can be closed. More related to **vcontrold** but good to have it identified and documented 😄.

**Comment by Alexandre-io** [comment]
:+1: thanks for the follow up
