### ISSUE TITLE
Security-related request: Do not expose 3002 by default

### ISSUE THREAD

**Issue by Schm1tz1** [Alexandre-io/homeassistant-vcontrol#19]
Hi,
I found that we are exposing 3002 on docker by default which is not needed in the local setup (connection is in local network / loopback of the container). So we can put **3002/tcp: null** by default (as e.g. MariaDB add-on is also doing).
This can be a security issues as the port is neither encrypted nor is any kind auf authentication being used. Restricting to local connections is a good thing IMHO. For remote stuff you can at least add iptables-whitelisting.
Will create a PR with the initial change - happy to hear your feedback / suggestions!

**Comment by Schm1tz1** [comment]
https://github.com/Alexandre-io/homeassistant-vcontrol/pull/20

**Comment by Alexandre-io** [comment]
Hi @Schm1tz1 ,

You are right, the exposed port was for debugging purposes only and should not be exposed by default. :+1:
