### ISSUE TITLE
AddOn does not try to connect

### ISSUE THREAD

**Issue by andyyyy2306** [Alexandre-io/homeassistant-vcontrol#38]
Hello !

Just migrating from domoticz to HA. I use my Rpi vcontrol since 5 years.
If i start die vcontrol addon, i only get this in log. No try to connect ?
![grafik](https://github.com/Alexandre-io/homeassistant-vcontrol/assets/46449594/924e6c75-516a-417a-b42f-dc0c0ac7289b)

My config
![grafik](https://github.com/Alexandre-io/homeassistant-vcontrol/assets/46449594/15cb6b98-61d1-4b51-88a7-6a45236d64d2)

Could someone help me pls ?

**Comment by MrIcemanLE** [comment]
Same here. I don't get values on the MQTT-Topic with an external vcontrold.
`tty: /dev/ttyUSB0
refresh: 30
device_id: 204C
mqtt_topic: openv_ha
debug: true
commands:
  - getTempA:FLOAT
  - getTempWWistOben:FLOAT
  - getTempWWistUnten:FLOAT
  - getTempWWsoll:FLOAT
  - getTempVList:FLOAT
  - getTempVLsoll:FLOAT
  - getTempPriVL:FLOAT
  - getTempPriRL:FLOAT
  - getTempVerdIn:FLOAT
  - getTempVerdOut:FLOAT
  - getTempExp1:FLOAT
  - getTempSekRL:FLOAT
  - getTempPuffer:FLOAT
  - getTempRaumNorSoll:FLOAT
  - getPumpeStatusHK1:FLOAT
  - getPumpeStatusWW:FLOAT
  - getStatusSekP:FLOAT
  - getPumpeStatusZirk:FLOAT
  - getStatusPriVent:FLOAT
  - getStatusPriPumpe:FLOAT
  - getStatusVerdichter:FLOAT
  - getBetriebArt:STRING
  - getNeigung:FLOAT
  - getNiveau:FLOAT
  - Jahresarbeitszahl:FLOAT
  - JahresarbeitszahlHeizen:FLOAT
  - COPWW-Betrieb:FLOAT
  - COPHeizbetrieb:FLOAT
  - JahresarbeitszahlWW:FLOAT
  - getEnergieFaktor:FLOAT
  - getEnergieHeizwaerme:FLOAT
  - getEnergieHeizwaermeWW:FLOAT
  - getEnergieHeizelektro:FLOAT
  - getEnergieWWelektro:FLOAT
  - getStarts:FLOAT
  - getLZWP:FLOAT
  - get1xWW:FLOAT
  - getSystemTime:FLOAT
  - getError0:STRING
  - getError1:STRING
  - getError2:STRING
  - getError3:STRING
  - getError4:STRING
  - getError5:STRING
  - getError6:STRING
  - getError7:STRING
  - getError8:STRING
  - getError9:STRING
  - getLZVerdSt1:FLOAT
  - getLZVerdSt2:FLOAT
  - getLZVerdSt3:FLOAT
  - getLZVerdSt4:FLOAT
  - getLZVerdSt5:FLOAT
vcontrol_host: 192.168.0.107
vcontrol_port: 3002`

**Comment by andyyyy2306** [comment]
Hi, i could not get it run, so i changed my RaspberryPi to ESP !
This works fine with HomeAssistant.

[https://github.com/openv/openv/wiki/ESPHome-Optolink](url)

andyyyy2306
