### ISSUE TITLE
[Question] Custom vito.xml required when connecting over network? 

### ISSUE THREAD

**Issue by kagehisa** [Alexandre-io/homeassistant-vcontrol#60]
I am sorry if this is not the place for it but I don't know where else I could ask this. 
I run a vcontrold instance with a modified `vito.xml` on a raspberry pi. I installed the Homeassistant addon according to the documentation and connected it via the `vcontrold host` setting. This works fine, i can do the basic commands and it pushes everything to my mqtt broker.
But what got me thinking is the last part of the documentation:
> Custom vito.xml configuration file
>
>The module use the config option (refer to https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-advanced-options) for mounting a custom configuration file. It verifies the existence of a 'vito.xml' file during startup.
>
>Ensure the file is placed in the specified path:
>
>config/vcontrold/vito.xml

Do the `vito.xml` on the raspberry and the `vito.xml` for the addon need to match? Is the `vito.xml` in the addon even required when connecting to a remote vcontrold instance?

This part really confuses me, could someone please help me with this question?

**Comment by dk1305hb** [comment]
If you use your own Vcontrold Host in the Vcontrol add-on config this part of the documentation has got no impact. It is not required for you to place a vito.xml in this path.
It is a possibility for all users that use the add-on included vcontrol instance (Vcontrold Host=localhost) to overwrite the standard delivered vito.xml.

**Comment by kagehisa** [comment]
Ok, thank you very much for this answer!
