### ISSUE TITLE
How to change addresses in vito.xml with this addon?

### ISSUE THREAD

**Issue by SaulGoodman1337** [Alexandre-io/homeassistant-vcontrol#77]
Hi,
I recently started using vcontrold as a Home Assistant addon and am currently wondering how it is possible to change values in the vito.xml file.

It seems like setBetriebsartM1 has a different address in my setup compared to what is defined in the vito.xml file.

I accessed the Docker container and modified the values in the vito.xml file there, but the changes do not seem to be persistent and are reverted after a restart.

What is the proper procedure for handling this in the Home Assistant addon?

Thanks !

**Comment by SaulGoodman1337** [comment]
https://github.com/Alexandre-io/homeassistant-vcontrol/issues/47#issuecomment-1785121088

**Comment by mxcxpx** [comment]
i would like also want to know ->  How to change addresses in vito.xml with this addon?
