### ISSUE TITLE
Feature request: Possibility to connect to remote vcontrold instead of running it locally

### ISSUE THREAD

**Issue by Schm1tz1** [Alexandre-io/homeassistant-vcontrol#9]
I had a feature in mind for setups where you use a RPi or ESP-device connected to the _Vitodens_:
A flag to switch between local _vcontrold_ or remote connection. Should be possible with one flag that decided whether to start _vcontrold_ and 2 connection settings that are passed to _vclient_ with defaults to localhost.

Discussion in the HA thread: https://community.home-assistant.io/t/viessmann-openv-vcontrold-client-optolink/496463/24?u=schm1tz1

Will have a look later - branch created: https://github.com/Schm1tz1/homeassistant-vcontrol/tree/remote-vcontrold

**Comment by Schm1tz1** [comment]
Please also see https://github.com/Schm1tz1/homeassistant-vcontrol/tree/remote-vcontrold - already tested in local setup with developer VM connecting to original vcontrold on RPi that is running HA and connected to Vitodens with an Optolink cable.

**Comment by Schm1tz1** [comment]
Created a PR: https://github.com/Alexandre-io/homeassistant-vcontrol/pull/10

**Comment by Alexandre-io** [comment]
That's a nice feature!
I was planning to test a similar solution with a TCP-SERIAL bridge (like https://github.com/openv/openv/wiki/ESP32-und-vcontrold-....-out-of-the-box) with the board https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware

**Comment by Alexandre-io** [comment]
This feature is available starting with the version 1.6.0. Thanks @Schm1tz1
